require('dotenv').config();
const axios = require('axios');

const apiKey = process.env.VIRUSTOTAL_API_KEY;
const baseUrl = 'https://www.virustotal.com/api/v3';

// List of URLs to scan
const urlsToScan = [
 "http://houkadaigakuin.com/css/webmail.konsoleh.co.za/emailSignIn_accountCUST_ID/konsoleh.sign_in/email.user/webmail.konsoleh.login.htm",
"http://muftizainulabideen.com/wp-admin/be/StandardV2/zyjviy2q=/",
"http://pilatesboutique.com.au/css/commlog/",
// "http://u.to/w2G7IA",
// "https://2m.ma/ar/",
// "https://7i.se/debitreview",
// "https://absorbed-neighborly-lyre.glitch.me/Pay-palsecurealerts.html",
// "https://actimerluider.firebaseapp.com/",
// "https://amberpine.site/924e51fb09663fed5b4af7db241c3153",
// "https://app.speedywaiver.io/fill/GxsUZ3DNyRqI2KYgzusi",
// "https://app.waiverelectronic.com/render/templateByRefId/6285d92a4ea2063b0d8e8efe",
// "https://autohaus.com.sv/.well-known/zendsdsoskds03212943/DHL-SAZI-AUTO/DHL-SAZI-AUTO/DHL-SAZI-AUTO/dhl/?i=i&0",
// "https://bahri-ambulanter-pflegedienst.de/ea81a724d12cdb1642a63b91af127860",
// "https://bflyer.app",
// "https://bitflyerjp.com/ja-login.php",
// "https://cdejl27wywlpneivx7vfia-on.drv.tw/block2/",
// "https://chomatruider.firebaseapp.com/",
// "https://clt1429508.bmetrack.com/c/l?u=DA1C0F6&e=1419778&c=15D004&t=1&l=7A634C07&email=xtTsItcRrE6F6hSsDwwwCoo0eRwtDrrX&seq=1",
// "https://costa-performance.online/kindex/albuquerqye/yeyrtretr/osbcoinss/malokiyresd/fufazasAzzi.html?id=",
// "https://dpdhuposts.top/track",
// "https://foreverfarley.com/M08yODZmOEwyZDBxOXA=",
// "https://ispsongo.ac.mz/aaheygreaa/PageUpdated/ampt.html?app=",
// "https://itsssl.com/Zqcp9",
// "https://jascruipler.web.app/",
// "https://knowing-merciful-toaster.glitch.me/polkghd.html",
// "https://kyc-bltflyer.web.app",
// "https://lahoyws2.com/wp-content/uploads/2024/04/R/compatlog/tracking/pag1.html",
// "https://main.d1uywey79p2cj9.amplifyapp.com/werrx01USAHTM/?bcda=034956-3836-66",
// "https://muftizainulabideen.com/wp-admin/be/StandardV2/zyjviy2q=/",
// "https://myhermes-sendungs.com/",
// "https://officelog253.knack.com/customerports",
// "https://qei.vhl.mybluehost.me/YS/DN/Login.php",
// "https://riveroaks.edu.pk/wp-includes/ed/",
// "https://s.id/newgpt5",
// "https://s3.amazonaws.com/appforest_uf/f1656457024772x767432166634618200/sun.html",
// "https://service-survey.vip/warranty",
// "https://smoton.com/irwsro47-lpid4tzr-qo1hjyo6-r25",
// "https://storage.cloud.google.com/indettn/oscman4.html",
// "https://storage.cloud.google.com/riltool/karasecondautoindex.html",
// "https://storageapi.fleek.co/09995281-88e7-402f-88a9-89d148c049bd-bucket/Mail.html",
// "https://storageapi.fleek.co/1feb1999-9414-490f-9fd9-660d6a626ce1-bucket/encrypttwopentttmrrmukart.html",
// "https://storageapi.fleek.co/9b907c30-dca7-4129-b75f-8cb44e5b5e06-bucket/index.html",
// "https://t.co/BEYYahj0KH",
// "https://t.co/BxNz3Re1Rf",
// "https://t.co/GmnTcF2cYi",
// "https://tinyurl.com/pcpdecrapifier",
// "https://updatepay.tempurl.host/so/clients/web/login.php?searchvalue=Z648470348HU&token=b92f8658ee9f15ca481b29480804e7b921d28f9f",
// "https://www-rooblox.com/users/1657067/profile",
// "https://www.kepeklian.fr/mm.php",
// "https://www.manitowocice.com/Media/Manitowocice/robux1.html",
// "https://www.seo-domain.net/0:gateway:checkout/2999994",
// "gosuslugi.agency",
// "coronavirus.app",
// "www.coronavirus.app",
// "zc11m.csb.app",
// "documents-download-almeida-3d331c.netlify.app",
// "dogecoin20-st.web.app",
// "kyc-bltflyer.web.app",
// "restore637908-coinbase-us.web.app",
// "zttmct-tlemp.web.app",
// "gocycle.com.au",
// "urbanandruraldesign.com.au",
//"wiflix.autos",
// "wiiflix.autos",
// "wiiflix.beauty",
// "wiflix.blog",
// "wiflix.boats",
// "coronatec.com.br",
// "item-trck-uk-royal-mail.dmaqpay.com.br",
// "coronavirus.cc",
// "covid19tracker.cc",
// "youareanidiot.cc",
// "discord.lossantossanto1.repl.co",
// "socialearn.co",
// "8vjejn.com",
// "8vpro.com",
// "8vproe.com",
// "8vproq.com",
// "8vpror.com",
// "8vpros.com",
// "8vprot.com",
// "8vprow.com",
// "absenpbz.com",
// "actionagainstcovid19.com",
// "coronavirus.oss-accelerate.aliyuncs.com",
// "alphaumi.com",
// "beritapb.com",
// "bitflyer-global.com",
// "business-facebook-covid19.com",
// "cheapcorona.com",
// "ciel-goshugi.com",
// "confirm-snet.com",
// "corona-explained.com",
// "corona-power.com",
// "corona-ratgeber.com",
// "coronaai.com",
// "coronaaway.com",
// "coronadetection.com",
// "coronado1991.com",
// "coronadobball.com",
// "coronadocapitalgroup.com",
// "coronadocommunityacupuncture.com",
// "coronadocreatives.com",
// "coronadodirectory.com",
// "coronadoo.com",
// "coronaperformancemotors.com",
// "coronavirus-map.com",
// "coronavirus-monitor.com",
// "coronavirus-realtime.com",
// "coronavirus-testing.com",
// "coronavirusbabys.com",
// "coronaviruscenters.com",
// "coronaviruscomms.com",
// "coronavirusforgyms.com",
// "coronavirushealthclinic.com",
// "coronavirusnet.com",
// "coronaviruspracticeupdate.com",
// "coronavirustechhandbook.com",
// "coronavirut.com",
// "coronavit.com",
// "covid19defense.com",
// "covid19japan.com",
// "covid19lascruces.com",
// "covid19mayhem.com",
// "covid19proof.com",
// "covid19wny.com",
// "covidquarantine.com",
// "dashenopticians.com",
// "sgp1.digitaloceanspaces.com",
// "directmessageviolation.com",
// "discordsgift.com",
// "discqrde.com",
// "dispatchweekly.com",
// "dofus-mmorpg.com",
// "dofusevents.com",
// "dofuspourlenoobs.com",
// "www.irsusa-tax.net.dogfoodkart.com",
// "easytogets.com",
// "epulze-live.com",
// "jocoly.esvnpe.com",
// "facebooks-copyright.com",
// "feenixlanguage.com",
// "rxzxssx.fiduciaracking.com",
// "coronavirus-2019.firebaseio.com",
// "coronavirus-266714.firebaseio.com",
// "coronavirus-3ffb2.firebaseio.com",
// "coronavirus-44a93.firebaseio.com",
// "coronavirus-53337.firebaseio.com",
// "coronavirus-54646.firebaseio.com",
// "coronavirus-a600f.firebaseio.com",
// "coronavirus-alert.firebaseio.com",
// "coronavirus-d526b.firebaseio.com",
// "coronavirus-d9a66.firebaseio.com",
// "coronavirus-daily-status.firebaseio.com",
// "coronavirus-eba7a.firebaseio.com",
// "coronavirus-protection-6d180.firebaseio.com",
// "coronavirus-statistics-710b6.firebaseio.com",
// "coronavirusmap-eb48d.firebaseio.com",
// "covid-19-6538f.firebaseio.com",
// "covid-19-app.firebaseio.com",
// "covid-19-e9057.firebaseio.com",
// "covid-19-healthlynked.firebaseio.com",
// "covid-19-live-news-statistics.firebaseio.com",
// "covid-19-lk-dev.firebaseio.com",
// "covid19-a71d9.firebaseio.com",
// "covid19-dd7f7.firebaseio.com",
// "covid19-fb3d9.firebaseio.com",
// "covid19map-269302.firebaseio.com",
// "flutter-covid19.firebaseio.com",
// "online-coronavirus-268608.firebaseio.com",
// "wuhancoronavirustracker-693c1.firebaseio.com",
// "getcoronavirusassistance.com",
// "109.197.125.34.bc.googleusercontent.com",
// "gosoogi.com",
// "help-media.com",
// "coronavirus-tracker-api.herokuapp.com",
// "iamcorona.com",
// "igobjectionservices.com",
// "krakenlogins.com",
// "kuispb.com",
// "localcoronavirus.com",
// "lovemachina.com",
// "newvity.com",
// "onlinesupportportal.com",
// "hu.pokist.otzo.com",
// "penlabuseoribute.com",
// "preview-domain.com",
// "psicmaggiecorona.com",
// "abobelnejgbeghrbghkbshgbshkfb.pythonanywhere.com",
// "adobebeiownwkjngrjwkenfjkewnf.pythonanywhere.com",
// "adobepewjgronjgnwkengkjwengrj.pythonanywhere.com",
// "borsbrietjblrenlgbrlenhjt.pythonanywhere.com",
// "freshloader.eu.pythonanywhere.com",
// "quicknotice.eu.pythonanywhere.com",
// "iengjwklengkhwebhfceref.pythonanywhere.com",
// "jkrngjkernghernhgtehjnhk.pythonanywhere.com",
// "pesjidgnojensjgerkhvjefdvs.pythonanywhere.com",
// "thenoticememoir.pythonanywhere.com",
// "wiadomoscionet.pythonanywhere.com",
// "reclaim-bittrex.com",
// "rinanft.com",
// "rxcovid.com",
// "steamcommunitc.com",
// "steamcomnnulty.com",
// "studentschoicedwi.com",
// "supportscontact.com",
// "surveysparrow.com",
// "the-fmovies.com",
// "thoughtworkis.com",
// "tokenukraine.com",
// "tokopb.com",
// "fmovies.us.com",
// "vaccine-coronavirus.com",
// "valoxino.com",
// "violationhelp.com",
// "vww-roblox.com",
// "wsetransport.com",
// "www-dofus.com",
// "www-dofus-touch.com",
// "www-rsblox.com",
// "wwwdofuspourlesnoobs.com",
// "xn--www-ofus-touch-j1b.com",
// "cpanel01wh.bkk1.cloud.z.com",
// "gosuslugi.contact",
// "fmoviesto.cyou",
// "wiflix.cyou",
// "coronasushi.com.de",
// "adobe-jhhkwjrnfjadenfrskbgjlsnfgjdfn.pages.dev",
// "adobeli.pages.dev",
// "ariamanonux03p.pages.dev",
// "att-mail.pages.dev",
// "begincellcdn.pages.dev",
// "blurverse.pages.dev",
// "borsbrietjblrenlgbrlenhjt.pages.dev",
// "cfgxgfxf.pages.dev",
// "chainsrectify.pages.dev",
// "claim-pork.pages.dev",
// "clfpages2.pages.dev",
// "dappsyncrectify.pages.dev",
// "debanksdefi.pages.dev",
// "decentralizedappauth.pages.dev",
// "decentrausdchartfil.pages.dev",
// "diamond-hands-halo.pages.dev",
// "doctored.pages.dev",
// "fq703w52zt.pages.dev",
// "iengjwklengkhwebhfceref.pages.dev",
// "ixs.pages.dev",
// "jgeb6c8queuspv.pages.dev",
// "jkrngjkernghernhgtehjnhk.pages.dev",
// "livedappsrestore.pages.dev",
// "looksrare-d1x.pages.dev",
// "lourdesthompsonnf1r6.pages.dev",
// "mi-d1m.pages.dev",
// "micro-service-alertc0277sb-dev-err.pages.dev",
// "micro-service-alertc0277sb-erro.pages.dev",
// "micro-soft-failed-error.pages.dev",
// "micro-soft-virus-alert-warning.pages.dev",
// "microsoft-error-pages-check-errors.pages.dev",
// "microsoft-help-and-services.pages.dev",
// "microsoft-sales-hhgdygfg-asd.pages.dev",
// "microsoft-suppor-number.pages.dev",
// "microsoft-support-alrt-altr-fds.pages.dev",
// "microsoft-support-alrt-altr-fds-098.pages.dev",
// "microsoft-support-alrt-altr87785.pages.dev",
// "microsoft-terms-policyalr.pages.dev",
// "mykeruais-assets-cubu45.pages.dev",
// "newwork-6oy.pages.dev",
// "nodesappfix-io.pages.dev",
// "oscarcampbellb1eoi.pages.dev",
// "pandoraprejeangw6.pages.dev",
// "paperhander.pages.dev",
// "paperhands-portfoliotracker-wallet.pages.dev",
// "pooh-moneydapps.pages.dev",
// "portal-platform.pages.dev",
// "proxysync.pages.dev",
// "rpcrecoveryhub.pages.dev",
// "sd-74h.pages.dev",
// "sontungmtpmaidinhnhe.pages.dev",
// "spacexlaunch.pages.dev",
// "swiftblockresolve.pages.dev",
// "sync-7xr.pages.dev",
// "syncblockrectification.pages.dev",
// "tesla-2ju.pages.dev",
// "tl-4-vente-privee-b1j.pages.dev",
// "ueajflnjejdrwklnvkenrwjgnlvrjldf.pages.dev",
// "uni-swap-protocols.pages.dev",
// "verifyandfixdapp.pages.dev",
// "webaqunarmail.pages.dev",
// "webmial.pages.dev",
// "win-defender-sec-64csvxxvxxvxx0x665.pages.dev",
// "woow-seguro-de-viajes.pages.dev",
// "pub-fa147a3cddd04e9588b0d0a71d6d87fb.r2.dev",
// "portalpaxum.cokiwe2297.workers.dev",
// "fmovies.direct",
// "gosuslugi.directory",
// "me2.do",
// "fmovies.email",
// "wasabiwallet.eu",
// "wiflix.eu",
// "gosuslugi.express",
// "123movies.faith",
// "wiflix.fit",
// "dofus-mmorpg.fr",
// "dofuspoulesnoobs.fr",
// "dofuspourlenoobs.fr",
// "dofuspourlesnoobs.fr",
// "dofustouch.fr",
// "www-papycha.fr",
// "zt-za.fr",
// "fmoviesto.gg",
// "disceord.gift",
// "discrods.gift",
// "disocrds.gift",
// "wiflix.guru",
// "bitflyer.sviluppo.host",
// "pobreflix.icu",
// "wiflix.icu",
// "wiflix.in",
// "gos-uslugi.info",
// "gosuslug.info",
// "wiflix.info",
// "rcubebit.bitbucket.io",
// "covid19.egreen.io",
// "covid19.tfone.ir",
// "wasabiwallet.is",
// "pescaturismocorona.it",
// "covid19.jp",
// "correos-update.life",
// "gosuslugi.life",
// "gosuslugi.live",
// "wiflix.makeup",
// "fmovies-to.me",
// "fmoviestv.me",
// "0ffice365-1drvve-oneauthmx1drive.glitch.me",
// "adobsmore.glitch.me",
// "discord-fake-nitro-expiriment.glitch.me",
// "faithful-cotton-blue.glitch.me",
// "materialistic-chain-chicory.glitch.me",
// "melodious-rift-castanet.glitch.me",
// "rightful-diamond-skiff.glitch.me",
// "water-opaque-expert.glitch.me",
// "we3bwebma1l-r0unclcube-web3nail-nailweb-deliv3ry.glitch.me",
// "covid-19.media",
// "covid19.media",
// "covid-19.miami",
// "wiflix.motorcycles",
// "ipv4.login.msa.akadns6.net",
// "vs.login.msa.akadns6.net",
// "calm-wave-01c7f9910.5.azurestaticapps.net",
// "bcryp.net",
// "bill-overdue.net",
// "corona-club.net",
// "coronavirustestfinders.net",
// "alili2020.ddns.net",
// "hovafmd.ddns.net",
// "gosusslugi.net",
// "ifmovies.net",
// "kadina-sidetesusma.net",
// "pcdecrapifier.net",
// "spiffcoin.net",
// "stearnconmunity.net",
// "fe-by01p-msa.trafficmanager.net",
// "lgin.msa.trafficmanager.net",
// "api.lgin.msa.trafficmanager.net",
// "xml.lgin.msa.trafficmanager.net",
// "gosuslugi.network",
// "wiflix.network",
// "coronavirusalert.news",
// "fmovies-to.online",
// "gosuslugii.online",
// "lokal-vr.online",
// "meldung-vols.online",
// "cdcgov.org",
// "2020logs.duckdns.org",
// "vahlallha.duckdns.org",
// "f-movie.org",
// "fmovies4.org",
// "tabitha-cambodia.org",
// "stopcoronavirus.us.org",
// "wiflix.org",
// "gosuslugi.page",
// "plesk.page",
// "thirsty-solomon.13-67-133-60.plesk.page",
// "www.hungry-poitras.13-93-165-215.plesk.page",
// "kind-villani.13-93-165-215.plesk.page",
// "serene-shirley.13-93-165-215.plesk.page",
// "www.serene-shirley.13-93-165-215.plesk.page",
// "silly-driscoll.13-93-165-215.plesk.page",
// "www.silly-driscoll.13-93-165-215.plesk.page",
// "vigilant-fermi.13-93-165-215.plesk.page",
// "34-125-197-109.plesk.page",
// "www.adoring-shamir.34-125-197-109.plesk.page",
// "amazing-poitras.34-125-197-109.plesk.page",
// "www.amazing-poitras.34-125-197-109.plesk.page",
// "awesome-wescoff.34-125-197-109.plesk.page",
// "bold-kalam.34-125-197-109.plesk.page",
// "brave-ramanujan.34-125-197-109.plesk.page",
// "ns2.brave-ramanujan.34-125-197-109.plesk.page",
// "charming-satoshi.34-125-197-109.plesk.page",
// "www.charming-satoshi.34-125-197-109.plesk.page",
// "cranky-kalam.34-125-197-109.plesk.page",
// "crazy-pare.34-125-197-109.plesk.page",
// "r.crazy-pare.34-125-197-109.plesk.page",
// "www.crazy-pare.34-125-197-109.plesk.page",
// "eloquent-lumiere.34-125-197-109.plesk.page",
// "epic-feynman.34-125-197-109.plesk.page",
// "festive-jones.34-125-197-109.plesk.page",
// "www.festive-jones.34-125-197-109.plesk.page",
// "focused-swirles.34-125-197-109.plesk.page",
// "gallant-kalam.34-125-197-109.plesk.page",
// "www.gallant-moser.34-125-197-109.plesk.page",
// "great-williamson.34-125-197-109.plesk.page",
// "www.great-williamson.34-125-197-109.plesk.page",
// "happy-antonelli.34-125-197-109.plesk.page",
// "happy-sutherland.34-125-197-109.plesk.page",
// "www.happy-sutherland.34-125-197-109.plesk.page",
// "hungry-ptolemy.34-125-197-109.plesk.page",
// "lnstagramhelp.hungry-ptolemy.34-125-197-109.plesk.page",
// "lnstagramhelpcenter.hungry-ptolemy.34-125-197-109.plesk.page",
// "www.hungry-ptolemy.34-125-197-109.plesk.page",
// "www.intelligent-gould.34-125-197-109.plesk.page",
// "www.jolly-jennings.34-125-197-109.plesk.page",
// "jolly-keldysh.34-125-197-109.plesk.page",
// "www.jolly-keldysh.34-125-197-109.plesk.page",
// "www.jolly-nightingale.34-125-197-109.plesk.page",
// "magical-kirch.34-125-197-109.plesk.page",
// "www.magical-kirch.34-125-197-109.plesk.page",
// "naughty-faraday.34-125-197-109.plesk.page",
// "nice-curran.34-125-197-109.plesk.page",
// "www.nifty-mahavira.34-125-197-109.plesk.page",
// "optimistic-wright.34-125-197-109.plesk.page",
// "www.optimistic-wright.34-125-197-109.plesk.page",
// "peaceful-carson.34-125-197-109.plesk.page",
// "pedantic-feynman.34-125-197-109.plesk.page",
// "pedantic-satoshi.34-125-197-109.plesk.page",
// "www.pensive-wing.34-125-197-109.plesk.page",
// "www.serene-hertz.34-125-197-109.plesk.page",
// "sharp-kowalevski.34-125-197-109.plesk.page",
// "www.sharp-kowalevski.34-125-197-109.plesk.page",
// "stoic-elion.34-125-197-109.plesk.page",
// "www.suspicious-wilson.34-125-197-109.plesk.page",
// "trusting-lumiere.34-125-197-109.plesk.page",
// "www.trusting-lumiere.34-125-197-109.plesk.page",
// "upbeat-elion.34-125-197-109.plesk.page",
// "xenodochial-liskov.34-125-197-109.plesk.page",
// "youthful-engelbart.34-125-197-109.plesk.page",
// "www.youthful-engelbart.34-125-197-109.plesk.page",
// "peaceful-joliot.45-136-204-40.plesk.page",
// "adoring-dhawan.45-138-72-99.plesk.page",
// "loving-chatelet.45-138-72-99.plesk.page",
// "recursing-perlman.45-156-26-247.plesk.page",
// "lucid-moser.45-156-27-107.plesk.page",
// "flamboyant-curran.52-148-188-66.plesk.page",
// "wonderful-carver.52-229-21-156.plesk.page",
// "competent-edison.95-181-157-141.plesk.page",
// "eager-pare.95-181-157-141.plesk.page",
// "goofy-lamport.95-181-157-21.plesk.page",
// "gracious-bardeen.95-181-157-21.plesk.page",
// "suspicious-meninsky.95-181-157-21.plesk.page",
// "vibrant-kirch.95-181-157-21.plesk.page",
// "loratech.pe",
// "vietnam.zing.photos",
// "corona-extra.pw",
// "plhn.pw",
// "wiflix.re",
// "accounts-mail.ru",
// "coronavirus-monitor.ru",
// "coronavirus-update.ru",
// "covideo.ru",
// "ecovida.ru",
// "gos-uslug.ru",
// "gosmslugi.ru",
// "gosrslugi.ru",
// "gossusluggi.ru",
// "gosulgi.ru",
// "gosulsugl.ru",
// "gosulugi-anticovid.ru",
// "gosulugl.ru",
// "gosulugy.ru",
// "gosulvgi.ru",
// "gosushlugi.ru",
// "gosusligu.ru",
// "gosusloogi.ru",
// "gosuslugee.ru",
// "gosuslugi-covid-qr.ru",
// "gosuslugi-kultura.ru",
// "gosuslugi-pay.ru",
// "gosuslugi-payment.ru",
// "gosuslugi2.ru",
// "gosuslugianticovid.ru",
// "gosuslugicovid-cert.ru",
// "gosuslugigov.ru",
// "gosuslugipay.ru",
// "gosuslugji.ru",
// "gosuslugt.ru",
// "gosusluslugi.ru",
// "gosusnugi.ru",
// "gosusrugi.ru",
// "grosuslugi.ru",
// "hotelsochipark.ru",
// "igosuslugi.ru",
// "sochi-park-otel.ru",
// "sochipark-hotel.ru",
// "verify-gosuslugi.ru",
// "vgosuslugi.ru",
// "wgosuslugi.ru",
// "www-gos-uslugi.ru",
// "gosuslugi.shop",
// "hellothere.shop",
// "sellskin.shop",
// "coronavirusapp.site",
// "fmovies2.site",
// "gos-uslygi.site",
// "fmovies.social",
// "gosuslugi.social",
// "bigbeans.solutions",
// "covid19x.solutions",
// "gosyslugi.su",
// "moscow-post.su",
// "www.moscow-post.su",
// "wiflix.tech",
// "coronavirus-update.today",
// "choicemonitor.top",
// "us-psues.top",
// "www.0202.com.tw",
// "gosuslugi.uk",
// "coronavirus.uno",
// "dating4free.us",
// "dating4sex.us",
// "perfectdating.us",
// "fmovies.vet",
// "corona77.vip",
// "souq-deals.website",
// "wiflix.work",
// "postcovid19.world",
// "gosuslugi.xyz",
// "soclaiemx.xyz",
// "wiflix.xyz",
// "wiflix.yachts",
// "coronavirus.zone"
];

// Function to scan a URL
async function scanUrl(url) {
  try {
    const response = await axios.post(`${baseUrl}/urls`, new URLSearchParams({ url }), {
      headers: {
        'x-apikey': apiKey,
        'Content-Type': 'application/x-www-form-urlencoded'
      }
    });

    const analysisId = response.data.data.id;
    console.log('URL Scan ID:', analysisId);
    return analysisId;
  } catch (error) {
    console.error('Error scanning URL:', error);
    return null;
  }
}

// Function to get the scan report
async function getScanReport(analysisId) {
  try {
    const response = await axios.get(`${baseUrl}/analyses/${analysisId}`, {
      headers: {
        'x-apikey': apiKey
      }
    });

    const report = response.data.data.attributes;
    //console.log('Scan Report:', report);

    // Analyze the scan report
    const maliciousCount = report.stats.malicious;
    const suspiciousCount = report.stats.suspicious;
    const harmlessCount = report.stats.harmless;
    const undetectedCount = report.stats.undetected;

    console.log(`Malicious: ${maliciousCount}, Suspicious: ${suspiciousCount}, Harmless: ${harmlessCount}, Undetected: ${undetectedCount}`);

    if (maliciousCount > 0) {
      console.log('The URL is malicious.');
    } else if (suspiciousCount > 0) {
      console.log('The URL is suspicious.');
    } else {
      console.log('The URL is good.');
    }
  } catch (error) {
    console.error('Error retrieving scan report:', error);
  }
}

// Main function to scan all URLs
async function main() {
  for (const url of urlsToScan) {
    console.log(`Scanning URL: ${url}`);
    const analysisId = await scanUrl(url);
    if (analysisId) {
      await getScanReport(analysisId);
    }
  }
}

main();
